logDir: plugins/ActivityTracker/logs

# use the player's primary group as a subdirectory?
logDirPerGroup: false

# log all inventory pickup/drop events to a central log?
allPickupDropLogging: true
# related to all pickup/drop logging: skip common single
# pickups? This avoids the log being spammed with people
# mining dirt, cobble, sand, etc
skipCommonSinglePickups: true

logMovement: true

# in seconds
logMovementInterval: 5

# you can choose whatever permissions you want, these are
# just examples
trackedPermissions:
- activitytracker.tracked
- group.Guest

debug: false
